spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_encomendas
spring.datasource.username=postgres
spring.datasource.password=scifoty

# Isso faz o Java criar as tabelas sozinho pra você
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true